refactor: Fixed bugs and added github action (#2)
* Fixed bugs

* Fixed cr

* Added more comments

diff --git a/.github/workflows/update_btfhub.yaml b/.github/workflows/update_btfhub.yaml
--- a/.github/workflows/update_btfhub.yaml
+++ b/.github/workflows/update_btfhub.yaml
@@ -12,6 +12,16 @@ jobs:
         distro: [ ubuntu, debian, centos, amazon, fedora ]
 
     steps:
+      - name: Check permissions
+        shell: bash
+        if: ${{ github.event_name == "workflow_dispatch" }}
+        run: |
+          array=(${{secrets.ALLOWED_PROD_DEPLOY_USERS}})
+          if [[ ! " ${array[*]} " =~ " ${{ github.actor }} " ]]; then
+          echo "::error ::'${{ github.actor }}' is not allowed to run this action!"
+          exit 1
+          fi
+
       - name: Fetch code
         uses: actions/checkout@v2
 
@@ -21,10 +31,14 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y dwarves lynx sqlite3 axel
 
-      - name: GCR prod auth
-        uses: google-github-actions/auth@v0.4.0
+      - uses: google-github-actions/setup-gcloud@v0
         with:
-          credentials_json: ${{ env.PROD_GCR_SA_KEY }}
+          project_id: seekret
+          service_account_key: ${{ secrets.PROD_GCR_SA_KEY }}
+          export_default_credentials: true
+
+      - name: Set up Cloud SDK
+        uses: google-github-actions/setup-gcloud@v0.2.1
 
       - name: Download
         run: |
